/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ******************************************* START
 * *********************************************** */
/* Libraries, Definitions and Global Declarations */
#include "main.h"
#include "EngTrModel.h"
#include "functions.h"
#include "ports.h"
#include <stdio.h>

int main(void) {

  ADC1_GPIO_Init();
  ADC1_Init();
  EngTrModel_initialize();

  for (;;) {
    EngTrModel_U.Throttle = adc_value;
    EngTrModel_U.BrakeTorque = 0;
    EngTrModel_step();

    double engine_speed = EngTrModel_Y.EngineSpeed;
    double vehicle_speed = EngTrModel_Y.VehicleSpeed;
    double gear = EngTrModel_Y.Gear;

    printf("Vehicle Speed: %f\r\n", vehicle_speed);
    printf("Engine Speed: %f\r\n", engine_speed);
    printf("Gear: %f\r\n", gear);
  }
}
