/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ******************************************* START
 * *********************************************** */
/* Libraries, Definitions and Global Declarations */
#include "main.h"
#include "EngTrModel.h"
#include "functions.h"
#include "lcd.h"
#include "motor.h"
#include "ports.h"
#include "pwm.h"
#include "timer.h"
#include "uart.h"
#include <stdio.h>

volatile uint8_t brake_active = 0;
volatile uint8_t task_flag = 0;

void TASK_Sensor_Init(void);
void TASK_Sensor(void);

void TASK_Controller_Init(void);
void TASK_Controller(void);

void TASK_Motor_Init(void);
void TASK_Motor(void);

void TASK_Display_Init(void);
void TASK_Display(void);

void TASK_Comm_Init(void);
void TASK_Comm(void);

// Note, we removed the IRQ handler because the instructions was to use a cyclic
// structure, but it is not the correct way to do it as it doesnt guarantee the
// 40ms timing.
int main(void) {

  SystemClock_Config();

  TASK_Sensor_Init();
  TASK_Controller_Init();
  TASK_Motor_Init();
  TASK_Display_Init();
  TASK_Comm_Init();

  for (;;) {
    TASK_Sensor();
    TASK_Controller();
    TASK_Motor();
    TASK_Display();
    TASK_Comm();
  }
}

void TASK_Sensor_Init(void) {
  ADC1_GPIO_Init();
  ADC1_Init();
  EXT_Button_Init();
}

// Note, the ADC value is handled by the interrupt, so we don't read it here.
// Instead, we just update the model inputs
void TASK_Sensor(void) { brake_active = EXT_BUTTON ? 1 : 0; }

void TASK_Controller_Init(void) { EngTrModel_initialize(); }

void TASK_Controller(void) {
  EngTrModel_U.Throttle = 1.5f + ((float)adc_value / 4095.0f) * 98.5f;
  EngTrModel_U.BrakeTorque = brake_active ? 100.0 : 0.0;
  EngTrModel_step();
}

void TASK_Motor_Init(void) {
  PWM_GPIO_Init();
  TIM2_PWM_Init();
  TIM4_PWM_Init();
  Motor_GPIO_Init();
  Motor_All_Forward();
}

void TASK_Motor(void) {
  double duty = (EngTrModel_Y.VehicleSpeed / 140.0) * 100.0;
  Change_Duty_Cycle_M1(duty);
  Change_Duty_Cycle_M2(duty);
  Change_Duty_Cycle_M3(duty);
  Change_Duty_Cycle_M4(duty);
}

void TASK_Display_Init(void) {
  LCD_Init();
  LCD_Clear();
  LCD_Set_Cursor(1, 1);
  LCD_Put_Str("Transmision Tractor");
}

void TASK_Display(void) {
  char line[17];

  snprintf(line, sizeof(line), "Ac:%4.0f   G:%u", (double)adc_value,
           (unsigned)EngTrModel_Y.Gear);
  LCD_Set_Cursor(1, 1);
  LCD_Put_Str(line);

  snprintf(line, sizeof(line), "Speed:%8.1f  ", EngTrModel_Y.VehicleSpeed);
  LCD_Set_Cursor(2, 1);
  LCD_Put_Str(line);
}

void TASK_Comm_Init(void) { USART1_Init(); }

void TASK_Comm(void) {
  char buffer[32];
  uint16_t len;

  len = snprintf(buffer, sizeof(buffer), "VS:%.2f\r\n",
                 EngTrModel_Y.VehicleSpeed);
  USART1_Transmit((uint8_t *)buffer, len);

  len =
      snprintf(buffer, sizeof(buffer), "ES:%.2f\r\n", EngTrModel_Y.EngineSpeed);
  USART1_Transmit((uint8_t *)buffer, len);

  len = snprintf(buffer, sizeof(buffer), "GR:%.2f\r\n", EngTrModel_Y.Gear);
  USART1_Transmit((uint8_t *)buffer, len);
}
