/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ******************************************* START
 * *********************************************** */
/* Libraries, Definitions and Global Declarations */
#include "main.h"
#include "EngTrModel.h"
#include "functions.h"
#include "lcd.h"
#include "motor.h"
#include "ports.h"
#include "pwm.h"
#include "timer.h"
#include "uart.h"
#include <stdio.h>


void Transmit_Data(void);

void TIM3_IRQHandler(void) {
  if (TIM3->SR & (0x1UL << 0U)) {
    TIM3->SR &= ~(0x1UL << 0U);

    EngTrModel_U.Throttle = 1.5f + ((float)adc_value / 4095.0f) * 98.5f;
    EngTrModel_U.BrakeTorque = EXT_BUTTON ? 100.0 : 0.0;
    EngTrModel_step();
  }
}

int main(void) {

  SystemClock_Config();
  USART1_Init();
  ADC1_GPIO_Init();
  ADC1_Init();
  EngTrModel_initialize();
  TIM3_Init();
  TIM3_40ms_Interrupt_Config();
  EXT_Button_Init();
  PWM_GPIO_Init();
  TIM2_PWM_Init();
  TIM4_PWM_Init();
  Motor_GPIO_Init();
  Motor_All_Forward();

  LCD_Init();
  LCD_Set_Cursor(1, 1);
  LCD_Put_Str("Transmision Tractor");
  LCD_Set_Cursor(2, 3);
  LCD_Clear();

  for (;;) {

    double duty = (EngTrModel_Y.VehicleSpeed / 140.0) * 100.0;
    Change_Duty_Cycle_M1(duty);
    Change_Duty_Cycle_M2(duty);
    Change_Duty_Cycle_M3(duty);
    Change_Duty_Cycle_M4(duty);

    Transmit_Data();

    char line[17];
    snprintf(line, sizeof(line), "Ac:%4.0f   G:%u", (double)adc_value,
             (unsigned)EngTrModel_Y.Gear);
    LCD_Set_Cursor(1, 1);
    LCD_Put_Str(line);

    snprintf(line, sizeof(line), "Speed:%8.1f  ", EngTrModel_Y.VehicleSpeed);
    LCD_Set_Cursor(2, 1);
    LCD_Put_Str(line);
  }
}

void Transmit_Data(void) {
  char buffer[32];
  uint16_t len;

  len = snprintf(buffer, sizeof(buffer), "VS:%.2f\r\n",
                 EngTrModel_Y.VehicleSpeed);
  USART1_Transmit((uint8_t *)buffer, len);
  len =
      snprintf(buffer, sizeof(buffer), "ES:%.2f\r\n", EngTrModel_Y.EngineSpeed);
  USART1_Transmit((uint8_t *)buffer, len);

  len = snprintf(buffer, sizeof(buffer), "GR:%.2f\r\n", EngTrModel_Y.Gear);
  USART1_Transmit((uint8_t *)buffer, len);
}
