/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ******************************************* START *********************************************** */
/* Libraries, Definitions and Global Declarations */
#include <stdint.h> // 							standard integer library
#include "main.h"
#include "user_keypad.h"

/* Superloop structure */
int main(void)
{
	/* Declarations and Initializations */
	USER_Keypad_Init(); //						initialize the keypad GPIO pins
	USER_GPIO_Init(); //						initialize the GPIO pins for the LEDs
	/* Repetitive block */
    for(;;){

		uint8_t key = USER_Key();
		if(key != 0xFF){
			USER_Delay_10ms();
			key = USER_Key();
			if(key != 0xFF){
				GPIOA->ODR = (key & 0x0F) << 4;
			}
		}
	}
}

void USER_GPIO_Init( void ){
	RCC->APB2ENR |= ( 0x1UL << 2U ); 

	// Configure PA4-PA7 as output push-pull
    for(int i = 4; i < 8; i++){
        GPIOA->CRL &= ~(0x3UL << (2U+(i * 4U))) & ~(0x2UL << (i * 4U)); // Clear CNF0[1:0] and MODE0_1 for PAi
        GPIOA->CRL |= (0x1UL << (i * 4U)); // Set MODE0_1 for PAi
    }
}

void USER_Delay_10ms( void ){
	__asm(" 		ldr r0, =1249999	");//	load the value to be used as delay count
	__asm(" again:	sub r0, r0, #1		");//	decrement the delay count
	__asm("			cmp r0, #0			");//	check if the delay count has reached zero
	__asm("			bne again			");//	if not, repeat the process
	__asm("			nop					");//	no operation (to ensure exact timing)
}

void USER_Delay_1sec( void ){
	__asm(" 		ldr r0, =7111111	");//	load the value to be used as delay count
	__asm(" again1:	sub r0, r0, #1		");//	decrement the delay count
	__asm("			cmp r0, #0			");//	check if the delay count has reached zero
	__asm("			bne again1			");//	if not, repeat the process
	__asm("			nop					");//	no operation (to ensure exact timing)
}